import {
  darkModePrimary,
  darkTextShadow,
  defaultShadow,
  error,
  lightModePrimary,
  lightTextShadow,
  neutral,
  success,
  warning,
} from './colors'
import { primaryFont, secondaryFont, typeScale } from './typography'

export const defaultTheme = {
  primaryColor: lightModePrimary[100],
  secondaryColor: lightModePrimary[200],
  largeHeadingTextColor: lightModePrimary[200],
  buttonText: lightModePrimary[200],
  navBarColor: neutral[100],
  sideBarColor: neutral[100],
  textColor: lightModePrimary[300],
  textColorOnPrimary: lightModePrimary[200],
  textColorOnSecondary: neutral[100],
  textColorInverted: neutral[100],
  textShadow: lightTextShadow,
  disabled: neutral[400],
  textOnDisabled: neutral[300],
  status: {
    warningColor: warning[100],
    warningColorHover: warning[200],
    warningColorActive: warning[300],
    errorColor: error[100],
    errorColorHover: error[200],
    errorColorActive: error[300],
    successColor: success[100],
    successColorHover: success[200],
    successColorActive: success[300],
  },
  primaryFont,
  secondaryFont,
  defaultShadow,
  typeScale,
}

export const darkTheme = {
  primaryColor: darkModePrimary[100],
  secondaryColor: darkModePrimary[200],
  largeHeadingTextColor: neutral[100],
  buttonText: neutral[100],
  navBarColor: 'none',
  sideBarColor: neutral[700],
  textColor: darkModePrimary[400],
  textColorOnPrimary: neutral[100],
  textColorOnSecondary: darkModePrimary[200],
  textColorInverted: neutral[100],
  textShadow: darkTextShadow,
  disabled: neutral[400],
  textOnDisabled: neutral[300],
  status: {
    warningColor: warning[100],
    warningColorHover: warning[200],
    warningColorActive: warning[300],
    errorColor: error[100],
    errorColorHover: error[200],
    errorColorActive: error[300],
    successColor: success[100],
    successColorHover: success[200],
    successColorActive: success[300],
  },
  primaryFont,
  secondaryFont,
  defaultShadow,
  typeScale,
}
